                                         week 3 

                                     Expiriment 3.1        

Aim: Write a NumPy program using methods info, add, array, all, greater, greater_equal, less and less_equal,equal, allclose, zeros, ones, linspace, tolist. a. To get help on the add function b. To test whether none of the elements of a given array is zero. c. To create an element-wise comparison (greater, greater_equal, less and less_equal, equal, equal within a tolerance) of two given arrays.

Description:
 This NumPy program demonstrates the use of various array functions such as info, add, array, all, greater, greater_equal, less, less_equal, equal, allclose, zeros, ones, linspace, and tolist. It performs operations to display help information for the add function, check whether an array contains any zeros, and compare two arrays element-wise using different comparison operators. It also shows how to create special arrays like zero-filled, one-filled, and evenly spaced arrays, and how to convert a NumPy array into a Python list.


Procedure / Algorithm:

1.	Import the NumPy library.
2.	Use the info() function to display details about the add() method.
3.	Create an array using np.array().
4.	Use the all() method with a comparison (arr != 0) to check if none of the elements are zero.
5.	Create two arrays for comparison.
6.	Use element-wise comparison functions (greater, greater_equal, less, less_equal, equal) on these .
7.	Use allclose() to check if arrays are approximately equal.
8.	Demonstrate creation of arrays using zeros(), ones(), and linspace().
9.	Convert one array to a list using tolist().
10.	Display all outputs.


In [1]:
# 3.1 (a)
from numpy import * 
print(add(1,2))


# 3.1 (b)

a=array([1,0,3,4])
print("the array is non zero:",all(a))


# 3.1 (c)
from numpy import * 
a=array([1,2,3])
b=array([3,2,1])
print(greater(a,b))
print(greater_equal(a,b))
print(less(a,b))
print(less_equal(a,b))
print(equal(a,b))
print(allclose(a,b))

3
the array is non zero: False
[False False  True]
[False  True  True]
[ True False False]
[ True  True False]
[False  True False]
False


                                     Expiriment 3.2        

Aim: Write a NumPy program using NumPy methods - max, min, argmax, argmin, argmax, repr, count, bincount, unique. a. To extract all numbers from a given array which are less and greater than a specified number. b. To find the indices of the maximum and minimum numbers along the given axis of an array

Description:
This NumPy program demonstrates the use of methods such as max, min, argmax, argmin, repr, count, bincount, and unique to perform different array operations. It extracts elements from an array that are less than or greater than a specified number, and finds the indices of maximum and minimum elements along a given axis. The program also shows how to count occurrences of numbers, display a string representation of an array, and find unique elements within it.


Procedure / Algorithm:

1.	Import the NumPy library.
2.	Create a NumPy array using array().
3.	Specify a number for comparison.
4.	Use conditional expressions to extract elements less than and greater than the given number.
5.	Use max() and min() to find the largest and smallest elements of the array.
6.	Use argmax() and argmin() to find the indices of the maximum and minimum values along a given axis.
7.	Use unique() to find unique elements from the array.
8.	Use bincount() to count occurrences of each element (for integer arrays).
9.	Use repr() to display the string representation of the array.
10.	Display all results.

In [2]:
# To extract elements from a NumPy array that are less than or greater than a specified number.
from numpy import *
a=array([10,20,30,40,50])
print(a[a!=30])



# To find the maximum and minimum values and their indices in a 2D array.


arr=array([[10,5,20],[80,60,30]])
arr
print(max(arr))
print(min(arr))
print(argmax(arr))
print(argmin(arr))
print(argmax(arr,axis=0))
print(argmax(arr,axis=1))
print(argmin(arr,axis=0))
print(argmin(arr,axis=1))

[10 20 40 50]
80
5
3
1
[1 1 1]
[2 0]
[0 0 0]
[1 2]
